# Generated by Django 2.2.4 on 2019-08-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_parties_voters'),
    ]

    operations = [
        migrations.AddField(
            model_name='parties',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
