# Generated by Django 2.1.3 on 2019-08-17 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_parties_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='voters',
            name='votingstatus',
            field=models.CharField(choices=[('voted', 'voted'), ('not voted', 'not voted')], default='not voted', max_length=50),
        ),
    ]
