# Generated by Django 2.2.3 on 2019-08-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_name', models.CharField(max_length=50)),
                ('aadhar_id', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('voting_status', models.CharField(choices=[('Voted', 'Voted'), ('Not Voted', 'Not Voted')], max_length=10)),
            ],
        ),
    ]
