# Generated by Django 2.2.4 on 2019-08-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elect', '0002_auto_20190809_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='parties',
            name='location',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
